### ISSUE TITLE
编译出错，rules.ini: 未找到命令

### ISSUE THREAD

**Issue by grick** [hightman/scws#1]
1. git clone file
2. run acprep
3. ./configure
4. sudo make install

结果出现错误

``` bash
Making install in etc
make[1]: 正在进入目录 `/home/abc/documents/C/scws/etc'
make[2]: 正在进入目录 `/home/abc/documents/C/scws/etc'
test -z "/usr/local/etc" || /bin/mkdir -p "/usr/local/etc"
  'rules.ini' '/usr/local/etc/f=rules.ini'
/bin/bash: 行 6: rules.ini: 未找到命令
  'rules.utf8.ini' '/usr/local/etc/f=rules.utf8.ini'
/bin/bash: 行 6: rules.utf8.ini: 未找到命令
  'rules_cht.utf8.ini' '/usr/local/etc/f=rules_cht.utf8.ini'
/bin/bash: 行 6: rules_cht.utf8.ini: 未找到命令
make[2]: *** [install-sysconfDATA] 错误 127
make[2]:正在离开目录 `/home/abc/documents/C/scws/etc'
make[1]: *** [install-am] 错误 2
make[1]:正在离开目录 `/home/abc/documents/C/scws/etc'
make: *** [install-recursive] 错误 1
```

从网站下载 bzip 包编译没问题。

**Comment by rngadam** [comment]
Still a problem.

On Ubuntu 14.04.1 LTS, I'm getting the same error referencing these non-existing rules.ini files.

```
~/scws-1.2.2$ automake --version
automake (GNU automake) 1.14.1
```

and

```
~/scws-1.2.2$ bash --version
GNU bash, version 4.3.11(1)-release (i686-pc-linux-gnu)
```

```

with this etc/Makefile:

```
# install sysconf_DATA
install-sysconfDATA:
        @$(NORMAL_INSTALL)
        test -z "$(sysconfdir)" || $(MKDIR_P) "$(DESTDIR)$(sysconfdir)"
        @list='$(sysconf_DATA)'; for p in $$list; do \
          if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
          f=$(am__strip_dir) \
          if test "$(DESTDIR)$(sysconfdir)/$$f" -nt "$$d$$p"; then \
            echo " Ignore exists sysconf data file '$$p'"; else \
            echo " $(sysconfDATA_INSTALL) '$$d$$p' '$(DESTDIR)$(sysconfdir)/$$f'"; \
            $(sysconfDATA_INSTALL) "$$d$$p" "$(DESTDIR)$(sysconfdir)/$$f"; \
          fi; \
        done  
```
