### ISSUE TITLE
请问支持mac 系统编译安装吗

### ISSUE THREAD

**Issue by 03128crz** [hightman/scws#13]
请问支持mac 系统编译安装吗

**Comment by hightman** [comment]
支持

Best Regards

hightman/海鳗
**********************************
微信/微博：hightman
Github：https://github.com/hightman

**Comment by 03128crz** [comment]
make 时出现以上warning 有影响吗？
scws.c:1523:35: warning: passing 'unsigned char *' to parameter of type 'const char *' converts between pointers to
      integer types with different sign [-Wpointer-sign]
                                top->word = (char *)_mem_ndup(s->txt + cur->off, cur->len);
                                                              ^~~~~~~~~~~~~~~~~
/usr/include/string.h:132:27: note: passing argument to parameter here
char    *strndup(const char *, size_t) __OSX_AVAILABLE_STARTING(__MAC_10_7, __IPHONE_4_3);
                             ^
scws.c:1533:54: warning: passing 'unsigned char *' to parameter of type 'const char *' converts between pointers to
      integer types with different sign [-Wpointer-sign]
                                xtree_nput(xt, top, sizeof(struct scws_topword), s->txt + cur->off, cur->len);
                                                                                 ^~~~~~~~~~~~~~~~~
./xtree.h:44:64: note: passing argument to parameter 'key' here
void xtree_nput(xtree_t xt, void *value, int vlen, const char *key, int len);

**Comment by hightman** [comment]
不影响

发自我的 iPhone6艹

**Comment by 03128crz** [comment]
好的，谢谢解答 :)
