### ISSUE TITLE
Enlgish word segmentation doesn't work.

### ISSUE THREAD

**Issue by shinbonlin** [hightman/scws#15]
I try to segment the word "happy birthday to you"

SCWS always return me only 1 array.

array(1) { [0]=> array(5) { ["word"]=> string(5) "happy" ["off"]=> int(0) ["len"]=> int(5) ["idf"]=> float(4.02359485626) ["attr"]=> string(2) "en" } }

How to fix this issue?

Thanks.

Ps. Chinese word segmentation works good.
Version: 1.2.2

**Comment by hightman** [comment]
You should repeatedly call `scws_get_result()` or `$scws->get_result()` until it returns `false`.

Best Regards

hightman/海鳗
**********************************
微信/微博：hightman
Github：https://github.com/hightman

**Comment by shinbonlin** [comment]
It works. Thanks for kindly replying.
