### ISSUE TITLE
支持php5.5或者更高的版本吗？

### ISSUE THREAD

**Issue by jianzi0307** [hightman/scws#16]
我看windows下的dll只支持到php5.4.x
能否提供更高版本的dll下载

**Comment by hightman** [comment]
需要自己编译，现在手上没win平台…囧

发自我的 iPhone6艹

**Comment by huangzhwork** [comment]
表示严重需要支持更高PHP版本的dll，PHP5.6的更佳，如果有人已经编译了的话有劳提供一下，谢谢

**Comment by hightman** [comment]
现在手头没 m$ 环境所以没再提供 dll ...

Best Regards

hightman/海鳗
**********************************
微信/微博：hightman
Github：https://github.com/hightman

**Comment by xeoshow** [comment]
同急需，5.5和5.6这个这么重要的版本，为啥不出dll呢？

**Comment by xeoshow** [comment]
我这里有环境，可是编译步骤如何做呢？可否有个文章或wiki?

**Comment by Timandes** [comment]
@xeoshow 
https://wiki.php.net/internals/windows/stepbystepbuild

**Comment by hightman** [comment]
其实没这么复杂，首先需要下载相应的 PHP 版本源码（用于 #include 头文件），然后将 scws-1.2.3 的源码和 php 的源码同级目录放置。
详见：scws-1.2.3 源码目录下的 win32/readme.txt，我以前也怕自己忘记了特意备忘过。

php-5.4 用的是 visual studio 2008，5.6和7.0不清楚是要哪个版本啦；在编译前其实可以直接用文本编辑器替换 scws.sln 中的相关版本号再用 vs 打开。


Best Regards

hightman/海鳗
**********************************
微信/微博：hightman
Github：https://github.com/hightman

**Comment by alexroyce315** [comment]
我今天尝试折腾编译 5.6 下的扩展文件，Windows 7 64Bit SP1 & VS2012 Express for Desktop，遭遇不少错误。 @Timandes 可否分享下经验，我搞这个单纯为了自己来玩下一个小项目，编译成功后会分享出来。

1>------ 已启动生成: 项目: libscws, 配置: Release Win32 ------
1>  scws.c
1>..\libscws\scws.c : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>h:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\xdict.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>..\libscws\scws.c(305): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\include\string.h(191) : 参见“strncpy”的声明
1>..\libscws\scws.c(310): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\include\string.h(191) : 参见“strncpy”的声明
1>..\libscws\scws.c(318): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\include\string.h(191) : 参见“strncpy”的声明
1>..\libscws\scws.c(323): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\include\string.h(191) : 参见“strncpy”的声明
1>..\libscws\scws.c(330): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\include\string.h(191) : 参见“strncpy”的声明
1>..\libscws\scws.c(353): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\include\string.h(191) : 参见“strncpy”的声明
1>..\libscws\scws.c(372): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\include\string.h(191) : 参见“strncpy”的声明
1>..\libscws\scws.c(446): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\include\string.h(191) : 参见“strncpy”的声明
1>..\libscws\scws.c(452): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\include\string.h(191) : 参见“strncpy”的声明
1>..\libscws\scws.c(486): error C2065: “SCWS_ZFLAG_ENGLISH”: 未声明的标识符
1>..\libscws\scws.c(494): error C2065: “SCWS_ZFLAG_ENGLISH”: 未声明的标识符
1>..\libscws\scws.c(566): error C2065: “SCWS_ZFLAG_ENGLISH”: 未声明的标识符
1>..\libscws\scws.c(571): error C2065: “SCWS_ZFLAG_ENGLISH”: 未声明的标识符
1>..\libscws\scws.c(587): error C2065: “SCWS_ZFLAG_ENGLISH”: 未声明的标识符
1>..\libscws\scws.c(636): error C2065: “SCWS_WORD_USED”: 未声明的标识符
1>..\libscws\scws.c(647): error C2065: “SCWS_WORD_RULE”: 未声明的标识符
1>..\libscws\scws.c(651): error C2065: “SCWS_WORD_USED”: 未声明的标识符
1>..\libscws\scws.c(671): error C2065: “SCWS_WORD_USED”: 未声明的标识符
1>..\libscws\scws.c(696): error C2065: “SCWS_WORD_USED”: 未声明的标识符
1>..\libscws\scws.c(802): error C2065: “SCWS_ZFLAG_ENGLISH”: 未声明的标识符
1>..\libscws\scws.c(803): warning C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>..\libscws\scws.c(814): warning C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>..\libscws\scws.c(822): error C2065: “SCWS_ZFLAG_SYMBOL”: 未声明的标识符
1>..\libscws\scws.c(871): error C2065: “SCWS_ZFLAG_NR2”: 未声明的标识符
1>..\libscws\scws.c(1428): warning C4113: “int (__cdecl *)()”和“int (__cdecl *)(const void *,const void *)”的参数列表不同
2>------ 已启动生成: 项目: scws, 配置: NonTS_PHP56 Win32 ------
2>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.CppBuild.targets(1137,5): warning MSB8012: TargetPath(H:\php-sdk\phpdev\vc11\x86\scws-1.2.3\win32\.\../Release\scws.dll) does not match the Linker's OutputFile property value (H:\php-sdk\phpdev\vc11\x86\scws-1.2.3\Release\php-5.6.30-nts\php_scws.dll). This may cause your project to build incorrectly. To correct this, please make sure that $(OutDir), $(TargetName) and $(TargetExt) property values match the value specified in %(Link.OutputFile).
2>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.CppBuild.targets(1139,5): warning MSB8012: TargetName(scws) does not match the Linker's OutputFile property value (php_scws). This may cause your project to build incorrectly. To correct this, please make sure that $(OutDir), $(TargetName) and $(TargetExt) property values match the value specified in %(Link.OutputFile).
2>LINK : fatal error LNK1181: 无法打开输入文件“libscws.lib”
========== 生成: 成功 0 个，失败 2 个，最新 0 个，跳过 0 个 ==========

**Comment by Timandes** [comment]
为什么你报错的那些位置，我并没有发现对应的代码呢？
