### ISSUE TITLE
使用拓展的形式，为什么时而函数，时而类方法呢？

### ISSUE THREAD

**Issue by ouewqa** [hightman/scws#18]
<?php
$sh = scws_open();
scws_set_charset($sh, 'gbk');

这里的scws_开头函数，是不是都是SimpleCWS的方法，上面的可以改写为

<?php
$sh = new scws_new;
$sh->open();
$sh->set_charset('gbk');

看文档，感觉有时用函数，有时用类，晕晕的。

如果是， new scws_new的时候，是不是就已经open了？

**Comment by hightman** [comment]
没有自己 new 的方法，有2种方法开始：

1. $sh = scws_open(); 返回的是一个 resource handle，必须用 scws_ 系列函数来后续；
2. $so = scws_new(); 返回的是一个 object，必须用 $so->xxx 系列方法来后续。

Best Regards

hightman/海鳗
**********************************
微信/微博：hightman
Github：https://github.com/hightman
