### ISSUE TITLE
Problem string

### ISSUE THREAD

**Issue by scottbouma** [hightman/scws#21]
I have uncovered a problem with certain strings in scws.  The simplest example I can find is "ｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏｏ", which causes an error on http://www.xunsearch.com/scws/demo/v48.php.

But if I remove a single character from the problem string, then it succeeds.

**Comment by hightman** [comment]
It seems this character is treated as english, I will track this issue, thanks.

**Comment by hightman** [comment]
A bit strange, I could not reproduce the BUG on MacOS.

**Comment by scottbouma** [comment]
Interesting.  We first encountered the issue when using the "zhparser"
extension for PostgreSQL (which relies on SCWS for tokenization). We are
running zhparser with PostgreSQL on Ubuntu, and the problem occurs there.

Thanks for looking into it.

**Comment by hightman** [comment]
@scottbouma hi, I just recompile libscws, and the problem actually gone. see:
<http://www.xunsearch.com/scws/demo/v48.php>

**Comment by scottbouma** [comment]
This is great!  Is there an updated binary that I can download and try out
on our system?

If so I can let you know in about 6 hours if it worked for us too.

**Comment by hightman** [comment]
Compiled on OS: ubuntu-14.04 (kernel  3.2.0-74)
<http://www.xunsearch.com/scws/demo/libscws.so.1.1.0>

**Comment by scottbouma** [comment]
Thanks for the fast reply!  Unfortunately the link above does not work.
I've attached a screenshot of the 404 error page.

We are currently downloading and building on Ubuntu using the following
commands:
wget -O - http://www.xunsearch.com/scws/down/scws-1.2.2.tar.bz2 | tar xvjf
-
cd /scws-1.2.2 && ./configure && make install

Are we using the correct version, and doing the right steps?  Did you do
anything special or different when you recompiled?

Thanks,
Scott

**Comment by hightman** [comment]
I am using scws-1.2.3-dev.


Best Regards

hightman/海鳗
**********************************
微信/微博：hightman
Github：https://github.com/hightman



> 在 2015年12月4日，上午12:44，scottbouma <notifications@github.com> 写道：
> 
> Thanks for the fast reply! Unfortunately the link above does not work.
> I've attached a screenshot of the 404 error page.
> 
> We are currently downloading and building on Ubuntu using the following
> commands:
> wget -O - http://www.xunsearch.com/scws/down/scws-1.2.2.tar.bz2 | tar xvjf
> -
> cd /scws-1.2.2 && ./configure && make install
> 
> Are we using the correct version, and doing the right steps? Did you do
> anything special or different when you recompiled?
> 
> Thanks,
> Scott
> 
> 
> 
>

**Comment by hightman** [comment]
Now I released 1.2.3, you can try it again...

**Comment by scottbouma** [comment]
Great, thanks for the update.
