### ISSUE TITLE
Can release out a php5.6 and 7 extension dll?php 5.4 is so old!!!

### ISSUE THREAD

**Issue by feeho** [hightman/scws#22]
Can release out a php5.6 and 7 extension dll?php 5.4 is so old!!!

**Comment by hightman** [comment]
sorry, I have not windows env now...

**Comment by feeho** [comment]
你好，在线？没有window环境我不太明白是何意！请问它表示系统装的不是windows?还是什么？目前生产环境应该都是5.6+的了。有几个vps上我装的已经是php7。在php5.4的时候用过scws，今天又须要这个功能。没想到在php5.6+扩展根本加载不了。试着用下纯php版本。结果一大堆错误。应该说php5.6+有较大的须求，自己也下载源码尝试编译。结果在windows下通不过。很久没用c了。基本忘完了。不知道大哥有没有考虑过编译一个？

**Comment by hightman** [comment]
编译需要visual studio环境，但是我手上没有。。。

**Comment by feeho** [comment]
大哥，我表示还是不太理解。没有visual studio环境这个含义，难道这不是下载+安装的事吗？毕竟对于不搞c的人来说。编译一个太难了。

**Comment by hightman** [comment]
平时不用windows，更谈不上安装了，那陀东西很大啊
