### ISSUE TITLE
centos 7 编译出错了

### ISSUE THREAD

**Issue by cxc222** [hightman/scws#27]
[root@localhost phpext]# ./configure --with-scws=/usr/local --with-php-config=/usr/local/php7/bin/php-config
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /usr/local/php7
checking for PHP includes... -I/usr/local/php7/include/php -I/usr/local/php7/include/php/main -I/usr/local/php7/include/php/TSRM -I/usr/local/php7/include/php/Zend -I/usr/local/php7/include/php/ext -I/usr/local/php7/include/php/ext/date/lib
checking for PHP extension directory... /usr/local/php7/lib/php/extensions/no-debug-non-zts-20151012
checking for PHP installed headers prefix... /usr/local/php7/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... re2c
checking for re2c version... 0.16 (ok)
checking for gawk... gawk
checking for scws support... yes, shared
checking for scws.h... no
configure: error: Please download and install scws from http://www.xunsearch.com/scws

编译php 7.0 
请问这是什么原因呢?

**Comment by Timandes** [comment]
`/usr/local`下有编译好的`scws`吗？

**Comment by cxc222** [comment]
没有的.
[root@localhost phpext]# ls /usr/local/
beanstalkd  doc          freetype  jpeg   libexec  mysql  php53  sbin   ssl
bin         ela_log_kib  games     lib    libpng   nginx  php56  share  tiff
boost       etc          include   lib64  man      pcre   php7   src    zlib
[root@localhost phpext]#

**Comment by Timandes** [comment]
囧，先编译`scws`吧。
然后--with-scws=后面接`scws`的目录。

**Comment by cxc222** [comment]
OK的.

**Comment by cxc222** [comment]
cd scws-1.2.3 ; ./configure ; make install

[root@localhost scws-1.2.3]# ./configure
bash: ./configure: No such file or directory

无法配置?

**Comment by Timandes** [comment]
官网下载源码包，不要从GitHub上下载。

**Comment by cxc222** [comment]
@Timandes 非常感谢, 终于安装成功了.

**Comment by cxc222** [comment]
@Timandes hello , 还有一个问题, 
Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; XTreeDB has a deprecated constructor in /mnt/hgfs/word/phptool_for_scws_xdb/xdb.class.php on line 118

XTreeDB class 是不是已经被移除了?

**Comment by Timandes** [comment]
See: http://php.net/manual/zh/migration70.deprecated.php
PHP7将PHP4风格的构造函数标记为`Deprecated`。
改成`__construct`就行了。

**Comment by cxc222** [comment]
@Timandes 感谢!!! 解决了我的问题

**Comment by Timandes** [comment]
不客气。关闭这个Issue吧，我没有权限……
