### ISSUE TITLE
add_dict貌似没起作用

### ISSUE THREAD

**Issue by cxc222** [hightman/scws#28]
代码如下:

> //测试分词
        $cws = scws_new();
        $cws->set_charset('utf8');
        // use default dictionary & rules
        //$cws->set_duality(false);
        //$cws->set_ignore(true);
        //$cws->set_multi(3);
        //$cws->set_rule(dirname(dirname(__FILE__)).'/conf/scws/rules/rules.utf8.ini');
        $cws->add_dict(dirname(dirname(__FILE__)).'/conf/scws/dict.utf8.xdb');
        $cws->add_dict(dirname(dirname(__FILE__)).'/conf/scws/dict.utf8.txt', SCWS_XDICT_TXT);
        $cws->send_text("JOHNBOSS 肖特 插刀架 5件套");
        $res = $cws->get_result();
        print_r($res);
        die;

dict.utf8.txt:
插刀架       2.0
5件套       1.0       1.0       @
JOHNBOSS           1.0      1.0    !

然而并没有 删除 'JOHNBOSS', 查询结果依然存在

> [root@localhost lib]# php console.php help
Array
(
    [0] => Array
        (
            [word] => JOHNBOSS
            [off] => 0
            [len] => 8
            [idf] => 5.1986036300659
            [attr] => en
        )

)
求解?

**Comment by hightman** [comment]
英文单词跟词典无关的。

Best Regards

hightman/海鳗
**********************************
微信/微博：hightman
Github：https://github.com/hightman

**Comment by cxc222** [comment]
@hightman 可是 插刀架 也没出来~

**Comment by hightman** [comment]
想用好一个东西，最好先看看文档。
$scws->get_result() 应该循环调用好吧？


Best Regards

hightman/海鳗
**********************************
微信/微博：hightman
Github：https://github.com/hightman

**Comment by cxc222** [comment]
@hightman 奥....sorry, 我忽略了这个地方写法...
