### ISSUE TITLE
windows下VC11编译php5.6.19的scws1.2.3出错。

### ISSUE THREAD

**Issue by hVenus** [hightman/scws#30]
操作系统： windows 10
VS:  Visual studio 2012
PHP:  php 5.6.19
SCWS: 1.2.3

按照文档里写的配置了编译环境，但是出错。提示如下：

> 
1>------ 已启动生成: 项目: libscws, 配置: Debug Win32 ------
1>  xtree.c
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\xtree.c : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\xtree.c(304): warning C4090: “函数”: 不同的“const”限定符
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\xtree.c(304): warning C4028: 形参 1 与声明不同
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\xtree.c(304): warning C4028: 形参 2 与声明不同
1>  xdict.c
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\xdict.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>d:\php-sdk\phpdev\vc11\x86\php-5.6.19-src\win32\unistd.h(3): error C2054: 在“PHPAPI”之后应输入“(”
1>d:\php-sdk\phpdev\vc11\x86\php-5.6.19-src\win32\unistd.h(3): error C2085: “usleep”: 不在形参表中
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\types.h(61): error C2085: “_ino_t”: 不在形参表中
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\types.h(65): error C2085: “ino_t”: 不在形参表中
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\types.h(74): error C2085: “_dev_t”: 不在形参表中
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\types.h(78): error C2085: “dev_t”: 不在形参表中
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\types.h(87): error C2085: “_off_t”: 不在形参表中
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\types.h(91): error C2085: “off_t”: 不在形参表中
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(27): warning C4079: 意外的标记“字符串”
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(27): warning C4081: 应输入“newline”；找到“)”
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(85): error C2016: C 要求一个结构或联合至少有一个成员
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(85): error C2061: 语法错误: 标识符“_dev_t”
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(86): error C2061: 语法错误: 标识符“st_ino”
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(86): error C2059: 语法错误:“;”
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(91): error C2061: 语法错误: 标识符“st_rdev”
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(91): error C2059: 语法错误:“;”
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(92): error C2061: 语法错误: 标识符“st_size”
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(92): error C2059: 语法错误:“;”
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(96): error C2059: 语法错误:“}”
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(101): error C2016: C 要求一个结构或联合至少有一个成员
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(101): error C2061: 语法错误: 标识符“_dev_t”
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(102): error C2061: 语法错误: 标识符“st_ino”
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(102): error C2059: 语法错误:“;”
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(107): error C2061: 语法错误: 标识符“st_rdev”
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(107): error C2059: 语法错误:“;”
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(108): error C2061: 语法错误: 标识符“st_size”
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(108): error C2059: 语法错误:“;”
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(109): error C2371: “st_atime”: 重定义；不同的基类型
1>          d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(93) : 参见“st_atime”的声明
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(110): error C2371: “st_mtime”: 重定义；不同的基类型
1>          d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(94) : 参见“st_mtime”的声明
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(111): error C2371: “st_ctime”: 重定义；不同的基类型
1>          d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(95) : 参见“st_ctime”的声明
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(112): error C2059: 语法错误:“}”
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(117): error C2016: C 要求一个结构或联合至少有一个成员
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(117): error C2061: 语法错误: 标识符“_dev_t”
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(118): error C2061: 语法错误: 标识符“st_ino”
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(118): error C2059: 语法错误:“;”
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(123): error C2061: 语法错误: 标识符“st_rdev”
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(123): error C2059: 语法错误:“;”
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(128): error C2059: 语法错误:“}”
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(131): error C2016: C 要求一个结构或联合至少有一个成员
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(131): error C2061: 语法错误: 标识符“_dev_t”
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(132): error C2061: 语法错误: 标识符“st_ino”
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(132): error C2059: 语法错误:“;”
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(137): error C2061: 语法错误: 标识符“st_rdev”
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(137): error C2059: 语法错误:“;”
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(138): error C2061: 语法错误: 标识符“st_size”
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(138): error C2059: 语法错误:“;”
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(139): error C2371: “st_atime”: 重定义；不同的基类型
1>          d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(93) : 参见“st_atime”的声明
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(140): error C2371: “st_mtime”: 重定义；不同的基类型
1>          d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(94) : 参见“st_mtime”的声明
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(141): error C2371: “st_ctime”: 重定义；不同的基类型
1>          d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(95) : 参见“st_ctime”的声明
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(142): error C2059: 语法错误:“}”
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(145): error C2016: C 要求一个结构或联合至少有一个成员
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(145): error C2061: 语法错误: 标识符“_dev_t”
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(146): error C2061: 语法错误: 标识符“st_ino”
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(146): error C2059: 语法错误:“;”
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(151): error C2061: 语法错误: 标识符“st_rdev”
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(151): error C2059: 语法错误:“;”
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(153): error C2371: “st_atime”: 重定义；不同的基类型
1>          d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(93) : 参见“st_atime”的声明
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(154): error C2371: “st_mtime”: 重定义；不同的基类型
1>          d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(94) : 参见“st_mtime”的声明
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(155): error C2371: “st_ctime”: 重定义；不同的基类型
1>          d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(95) : 参见“st_ctime”的声明
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(156): error C2059: 语法错误:“}”
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.inl(53): error C2027: 使用了未定义类型“stat”
1>          d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(100) : 参见“stat”的声明
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.inl(53): error C2027: 使用了未定义类型“_stat64i32”
1>          d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(130) : 参见“_stat64i32”的声明
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.inl(58): error C2027: 使用了未定义类型“stat”
1>          d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(100) : 参见“stat”的声明
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.inl(58): error C2027: 使用了未定义类型“_stat64i32”
1>          d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(130) : 参见“_stat64i32”的声明
1>d:\program files (x86)\microsoft visual studio 11.0\vc\include\sys\stat.h(246): warning C4161: #pragma pack(pop...) : 出栈的比入栈的多
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\xdict.c(117): error C2079: “st1”使用未定义的 struct“stat”
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\xdict.c(117): error C2079: “st2”使用未定义的 struct“stat”
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\xdict.c(121): warning C4133: “函数”: 从“int *”到“stat *”的类型不兼容
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\xdict.c(136): warning C4133: “函数”: 从“int *”到“stat *”的类型不兼容
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\xdict.c(136): error C2224: “.st_mtime”的左侧必须具有结构/联合类型
1>  xdb.c
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\xdb.c : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\xdb.c(60): warning C4996: 'lseek': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _lseek. See online help for details.
1>          d:\program files (x86)\microsoft visual studio 11.0\vc\include\io.h(313) : 参见“lseek”的声明
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\xdb.c(61): warning C4996: 'read': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _read. See online help for details.
1>          d:\program files (x86)\microsoft visual studio 11.0\vc\include\io.h(316) : 参见“read”的声明
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\xdb.c(135): warning C4996: 'open': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _open. See online help for details.
1>          d:\program files (x86)\microsoft visual studio 11.0\vc\include\io.h(315) : 参见“open”的声明
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\xdb.c(150): warning C4996: 'close': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _close. See online help for details.
1>          d:\program files (x86)\microsoft visual studio 11.0\vc\include\io.h(305) : 参见“close”的声明
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\xdb.c(156): warning C4996: 'lseek': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _lseek. See online help for details.
1>          d:\program files (x86)\microsoft visual studio 11.0\vc\include\io.h(313) : 参见“lseek”的声明
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\xdb.c(158): warning C4996: 'read': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _read. See online help for details.
1>          d:\program files (x86)\microsoft visual studio 11.0\vc\include\io.h(316) : 参见“read”的声明
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\xdb.c(163): warning C4996: 'close': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _close. See online help for details.
1>          d:\program files (x86)\microsoft visual studio 11.0\vc\include\io.h(305) : 参见“close”的声明
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\xdb.c(207): warning C4996: 'open': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _open. See online help for details.
1>          d:\program files (x86)\microsoft visual studio 11.0\vc\include\io.h(315) : 参见“open”的声明
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\xdb.c(232): warning C4996: 'lseek': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _lseek. See online help for details.
1>          d:\program files (x86)\microsoft visual studio 11.0\vc\include\io.h(313) : 参见“lseek”的声明
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\xdb.c(233): warning C4996: 'write': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _write. See online help for details.
1>          d:\program files (x86)\microsoft visual studio 11.0\vc\include\io.h(321) : 参见“write”的声明
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\xdb.c(254): warning C4996: 'lseek': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _lseek. See online help for details.
1>          d:\program files (x86)\microsoft visual studio 11.0\vc\include\io.h(313) : 参见“lseek”的声明
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\xdb.c(255): warning C4996: 'write': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _write. See online help for details.
1>          d:\program files (x86)\microsoft visual studio 11.0\vc\include\io.h(321) : 参见“write”的声明
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\xdb.c(258): warning C4996: 'close': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _close. See online help for details.
1>          d:\program files (x86)\microsoft visual studio 11.0\vc\include\io.h(305) : 参见“close”的声明
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\xdb.c(309): warning C4996: 'lseek': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _lseek. See online help for details.
1>          d:\program files (x86)\microsoft visual studio 11.0\vc\include\io.h(313) : 参见“lseek”的声明
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\xdb.c(310): warning C4996: 'write': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _write. See online help for details.
1>          d:\program files (x86)\microsoft visual studio 11.0\vc\include\io.h(321) : 参见“write”的声明
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\xdb.c(315): warning C4996: 'lseek': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _lseek. See online help for details.
1>          d:\program files (x86)\microsoft visual studio 11.0\vc\include\io.h(313) : 参见“lseek”的声明
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\xdb.c(316): warning C4996: 'write': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _write. See online help for details.
1>          d:\program files (x86)\microsoft visual studio 11.0\vc\include\io.h(321) : 参见“write”的声明
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\xdb.c(335): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          d:\program files (x86)\microsoft visual studio 11.0\vc\include\string.h(191) : 参见“strncpy”的声明
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\xdb.c(338): warning C4996: 'lseek': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _lseek. See online help for details.
1>          d:\program files (x86)\microsoft visual studio 11.0\vc\include\io.h(313) : 参见“lseek”的声明
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\xdb.c(339): warning C4996: 'write': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _write. See online help for details.
1>          d:\program files (x86)\microsoft visual studio 11.0\vc\include\io.h(321) : 参见“write”的声明
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\xdb.c(340): warning C4996: 'write': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _write. See online help for details.
1>          d:\program files (x86)\microsoft visual studio 11.0\vc\include\io.h(321) : 参见“write”的声明
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\xdb.c(345): warning C4996: 'lseek': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _lseek. See online help for details.
1>          d:\program files (x86)\microsoft visual studio 11.0\vc\include\io.h(313) : 参见“lseek”的声明
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\xdb.c(346): warning C4996: 'write': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _write. See online help for details.
1>          d:\program files (x86)\microsoft visual studio 11.0\vc\include\io.h(321) : 参见“write”的声明
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\xdb.c(530): warning C4996: 'lseek': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _lseek. See online help for details.
1>          d:\program files (x86)\microsoft visual studio 11.0\vc\include\io.h(313) : 参见“lseek”的声明
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\xdb.c(531): warning C4996: 'write': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _write. See online help for details.
1>          d:\program files (x86)\microsoft visual studio 11.0\vc\include\io.h(321) : 参见“write”的声明
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\xdb.c(566): warning C4113: “int (__cdecl *)()”和“int (__cdecl *)(const void *,const void *)”的参数列表不同
1>  scws.c
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\scws.c : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\xdict.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\scws.c(305): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          d:\program files (x86)\microsoft visual studio 11.0\vc\include\string.h(191) : 参见“strncpy”的声明
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\scws.c(310): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          d:\program files (x86)\microsoft visual studio 11.0\vc\include\string.h(191) : 参见“strncpy”的声明
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\scws.c(318): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          d:\program files (x86)\microsoft visual studio 11.0\vc\include\string.h(191) : 参见“strncpy”的声明
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\scws.c(323): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          d:\program files (x86)\microsoft visual studio 11.0\vc\include\string.h(191) : 参见“strncpy”的声明
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\scws.c(330): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          d:\program files (x86)\microsoft visual studio 11.0\vc\include\string.h(191) : 参见“strncpy”的声明
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\scws.c(353): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          d:\program files (x86)\microsoft visual studio 11.0\vc\include\string.h(191) : 参见“strncpy”的声明
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\scws.c(372): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          d:\program files (x86)\microsoft visual studio 11.0\vc\include\string.h(191) : 参见“strncpy”的声明
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\scws.c(446): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          d:\program files (x86)\microsoft visual studio 11.0\vc\include\string.h(191) : 参见“strncpy”的声明
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\scws.c(452): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          d:\program files (x86)\microsoft visual studio 11.0\vc\include\string.h(191) : 参见“strncpy”的声明
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\scws.c(486): error C2065: “SCWS_ZFLAG_ENGLISH”: 未声明的标识符
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\scws.c(494): error C2065: “SCWS_ZFLAG_ENGLISH”: 未声明的标识符
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\scws.c(566): error C2065: “SCWS_ZFLAG_ENGLISH”: 未声明的标识符
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\scws.c(571): error C2065: “SCWS_ZFLAG_ENGLISH”: 未声明的标识符
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\scws.c(587): error C2065: “SCWS_ZFLAG_ENGLISH”: 未声明的标识符
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\scws.c(636): error C2065: “SCWS_WORD_USED”: 未声明的标识符
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\scws.c(647): error C2065: “SCWS_WORD_RULE”: 未声明的标识符
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\scws.c(651): error C2065: “SCWS_WORD_USED”: 未声明的标识符
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\scws.c(671): error C2065: “SCWS_WORD_USED”: 未声明的标识符
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\scws.c(696): error C2065: “SCWS_WORD_USED”: 未声明的标识符
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\scws.c(802): error C2065: “SCWS_ZFLAG_ENGLISH”: 未声明的标识符
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\scws.c(822): error C2065: “SCWS_ZFLAG_SYMBOL”: 未声明的标识符
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\scws.c(871): error C2065: “SCWS_ZFLAG_NR2”: 未声明的标识符
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\scws.c(1428): warning C4113: “int (__cdecl *)()”和“int (__cdecl *)(const void *,const void *)”的参数列表不同
1>  rule.c
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\rule.c(45): warning C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          d:\program files (x86)\microsoft visual studio 11.0\vc\include\stdio.h(218) : 参见“fopen”的声明
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\rule.c(68): warning C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          d:\program files (x86)\microsoft visual studio 11.0\vc\include\string.h(110) : 参见“strcpy”的声明
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\rule.c(71): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          d:\program files (x86)\microsoft visual studio 11.0\vc\include\string.h(191) : 参见“strncpy”的声明
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\rule.c(222): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          d:\program files (x86)\microsoft visual studio 11.0\vc\include\string.h(191) : 参见“strncpy”的声明
1>  pool.c
1>  lock.c
1>d:\php-sdk\phpdev\vc11\x86\scws-1.2.3\libscws\lock.h(38): warning C4005: “EWOULDBLOCK”: 宏重定义
1>          d:\program files (x86)\microsoft visual studio 11.0\vc\include\errno.h(132) : 参见“EWOULDBLOCK”的前一个定义
1>  darray.c
1>  crc32.c
1>  charset.c
1>  正在生成代码...
2>------ 已启动生成: 项目: scws, 配置: Debug_PHP53 Win32 ------
2>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.CppBuild.targets(1137,5): warning MSB8012: TargetPath(D:\php-sdk\phpdev\vc11\x86\scws-1.2.3\win32\.\../Debug\scws.dll) does not match the Linker's OutputFile property value (D:\php-sdk\phpdev\vc11\x86\scws-1.2.3\Debug\php-5.3.x\php_scws.dll). This may cause your project to build incorrectly. To correct this, please make sure that $(OutDir), $(TargetName) and $(TargetExt) property values match the value specified in %(Link.OutputFile).
2>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.CppBuild.targets(1139,5): warning MSB8012: TargetName(scws) does not match the Linker's OutputFile property value (php_scws). This may cause your project to build incorrectly. To correct this, please make sure that $(OutDir), $(TargetName) and $(TargetExt) property values match the value specified in %(Link.OutputFile).
2>LINK : fatal error LNK1181: 无法打开输入文件“libscws.lib”
========== 生成: 成功 0 个，失败 2 个，最新 0 个，跳过 0 个 ==========

> 

求指教！！！

**Comment by hVenus** [comment]
为毛clone的代码编译不通过？
哎~~~~~
（centos 6.5 and freebsd 10）

**Comment by hVenus** [comment]
没啥用处。

> 1>d:\php-sdk\phpdev\vc11\x86\php-5.6.19-src\win32\unistd.h(3): error C2054: 在“PHPAPI”之后应输入“(

这个错误是什么导致的？谁知道？

**Comment by hightman** [comment]
你要跟着看下源码里 unistd.h 第3 行  PHPAPI 后面是什么，这些宣告很多是为了兼容性，如果明确知道意思可以直接暴力修改一下。

Best Regards

hightman/海鳗
**********************************
微信/微博：hightman
Github：https://github.com/hightman

**Comment by hVenus** [comment]
unistd.h 里的内容全在这儿了。

`#ifndef _PHP_WIN32_UNISTD_H
#define _PHP_WIN32_UNISTD_H PHPAPI int usleep(unsigned int useconds);
#endif
`

这方面不是很熟悉，望指点。

**Comment by hightman** [comment]
试试把 PHPAPI 去掉

Best Regards

hightman/海鳗
**********************************
微信/微博：hightman
Github：https://github.com/hightman

**Comment by hVenus** [comment]
关掉了。除了那个头文件的问题之外，其它的只是没有编译环境而已。
需要搞一个php的编译环境，起码先得能把php5ts.dll编译出来。不然各种报错。
多谢各位关注。

**Comment by Timandes** [comment]
@hVenus 如若方便，可否将编译产出的DLL提交至项目 https://github.com/Timandes/php-scws-win32 呢？
不胜感激。

**Comment by hVenus** [comment]
可以的。我先测试下能否可用。

发送自我的HTC Phone

----- 回复信息 -----
发件人： "Timandes White" <notifications@github.com>
收件人： "hightman/scws" <scws@noreply.github.com>
抄送： "ZhuMengxi" <kevin@fm618.com>, "Mention" <mention@noreply.github.com>
主题： [hightman/scws] windows下VC11编译php5.6.19的scws1.2.3出错。 (#30)
日期： 周五, 6月 3 日, 2016 年 13:26

@hVenus 如若方便，可否将编译产出的DLL提交至项目 https://github.com/Timandes/php-scws-win32 呢？

不胜感激。

&mdash;You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Timandes** [comment]
:+1: 多谢。
