### ISSUE TITLE
导入分词的php工具为啥报错呢

### ISSUE THREAD

**Issue by zhuCheer** [hightman/scws#36]
将xdb导出成txt是可以的，但是再导回去就会包notice错误数据下标未定义啥的，

![qq 20160711191559](https://cloud.githubusercontent.com/assets/5835853/16728968/2f08ad7c-479c-11e6-9fd8-c522712c14d2.png)

看了下代码make_xdb_file.php 
这个$word并不会是一个数组吧
![qq 20160711191541](https://cloud.githubusercontent.com/assets/5835853/16728979/4110d472-479c-11e6-8f05-a8dbd4646c69.jpg)

**Comment by hightman** [comment]
这个PHP工具太过于沉旧，无暇顾及了
