### ISSUE TITLE
scws编译没问题，测试也没问题，php7.0扩展编译安装都正常，但是phpinfo里出不来

### ISSUE THREAD

**Issue by mountainguan** [hightman/scws#46]
scws编译没问题，测试也没问题，php7.0扩展编译安装都正常，但是phpinfo里出不来

**Comment by lengyuan** [comment]
碰到同样问题了
php 7.1.20

**Comment by mountainguan** [comment]
@lengyuan 目测已经没人维护了，我试了一下php7.0可以使用那个叫pscws4的php实现版插件，性能好像低一些。或者直接用shell()方法封装命令行功能

**Comment by Timandes** [comment]
可否贴下php.ini相关配置？php -m的结果？以及版本信息？

**Comment by askie** [comment]
> [PHP Modules]
bcmath
Core
ctype
curl
date
dom
fileinfo
filter
ftp
gd
hash
iconv
json
libxml
mbstring
mcrypt
mysqli
mysqlnd
nsq
openssl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
redis
Reflection
session
SimpleXML
SPL
sqlite3
standard
swoole
tokenizer
xml
xmlreader
xmlwriter
zlib

[Zend Modules]

**Comment by mountainguan** [comment]
I finally get it work. Using `/usr/local/scws ; make ; make install` after phpize.
