### ISSUE TITLE
版本不同切词也不同了 

### ISSUE THREAD

**Issue by goith** [hightman/scws#50]
1.2.3
scws  -M 9  -i '汪蛋'  -c utf8  -d etc/dict.utf8.xdb  -r etc/rules.utf8.ini 
汪 蛋 
+--[scws(scws-cli/1.2.3)]----------+
1.2.1
 ./bin/scws -M 9  -i '汪蛋'  -c utf8  -d etc/dict.utf8.xdb  -r etc/rules.utf8.ini 
汪蛋 汪 蛋 
+--[scws(scws-cli/1.2.1)]----------+

请问，这个我怎么解决好？

**Comment by waitingsong** [comment]
dict.utf8.xdb 可能不同版本吧

**Comment by goith** [comment]
我是把1.2.1的拷过来了试的的，按说，高版本切词更优一些。

**Comment by hightman** [comment]
-M9 就代表复合切法，汪蛋应该是被识别成人名了
