### ISSUE TITLE
Mingw编译安装SCWS报错

### ISSUE THREAD

**Issue by Elvatao** [hightman/scws#51]
我需要在postgresql中集成中文全文检索功能，按照网站建议利用Mingw编译安装SCWS，
 ./configure时没有问题；
 make install结果报错：
in file included from scws.c:13:0:
config_win32.h:19:19: error:expected identifier or '<' before 'float'
 #define logf(x) ((float) log((double)(x)))
...
是在找不到错误在哪，请指点下，万分感谢了

**Comment by jk0011** [comment]
使用mingw64编译而不是mingw32，最好从cygwin安装mingw64。
