### ISSUE TITLE
No word segmentation

### ISSUE THREAD

**Issue by donnekgit** [hightman/scws#52]
I've downloaded and compiled scws (Ubuntu 14.04).

If I run it at the commandline, I get no segmentation:
```
$ scws -c utf8 '她令人紧张不 安。'
她  令  人  紧  张  不  安 。
```
instead of what I would expect (and which I get on the [webdemo](http://www.xunsearch.com/scws/demo/v48.php)):
```
她  令人  紧张  不  安 。
```

Do I need to do anything else to configure scws?

**Comment by hightman** [comment]
you should specify dictionary file bypass option ‘-d’

发自我的 iPhone6艹

**Comment by donnekgit** [comment]
```
$ scws -c utf8 -d '她令人紧张不 安。'
WARNING: failed to add dict file: 她令人紧张不 安。
```
Do I need to install the dictionary separately?

**Comment by donnekgit** [comment]
In fact, the dictionary doesn't seem to be in the scws-1.2.3 download.  What you have to do is (for the utf8 dictionary):
```
wget http://www.xunsearch.com/scws/down/scws-dict-chs-utf8.tar.bz2
tar xvjf scws-dict-chs-utf8.tar.bz2
```
as set out [here](http://www.xunsearch.com/scws/docs.php#instscws).  Then:
```
$ scws -c utf8 -d ../dict.utf8.xdb '她令人紧张不安。'
```
gives the expected output.
