### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by skipify** [hightman/scws#54]
CentOS release 6.9 (Final)
PHP 7.2.6
 

.libs/php_scws.o
/root/scws-1.2.1/phpext/php_scws.c: 在函数‘php_scws_dtor’中:
/root/scws-1.2.1/phpext/php_scws.c:145: 错误：‘rsrc’未声明(在此函数内第一次使用)
/root/scws-1.2.1/phpext/php_scws.c:145: 错误：(即使在一个函数内多次出现，每个未声明的标识符在其
/root/scws-1.2.1/phpext/php_scws.c:145: 错误：所在的函数内也只报告一次。)
/root/scws-1.2.1/phpext/php_scws.c: 在函数‘zif_scws_new’中:
/root/scws-1.2.1/phpext/php_scws.c:278: 警告：传递‘add_property_resource_ex’的第 4 个参数时将整数赋给指针，未作类型转换
/usr/local/php/include/php/Zend/zend_API.h:471: 附注：需要类型‘struct zend_resource *’，但实参的类型为‘int’
/root/scws-1.2.1/phpext/php_scws.c: 在函数‘zif_scws_close’中:
/root/scws-1.2.1/phpext/php_scws.c:288: 警告：传递‘zend_hash_find’的第 2 个参数时在不兼容的指针类型间转换
/usr/local/php/include/php/Zend/zend_hash.h:168: 附注：需要类型‘struct zend_string *’，但实参的类型为‘char *’
/root/scws-1.2.1/phpext/php_scws.c:288: 错误：提供给函数‘zend_hash_find’的实参太多
/root/scws-1.2.1/phpext/php_scws.c:288: 警告：比较指针和整数
/root/scws-1.2.1/phpext/php_scws.c:298: 错误：expected expression before ‘struct’
/root/scws-1.2.1/phpext/php_scws.c:300: 警告：传递‘zend_list_delete’的第 1 个参数时将整数赋给指针，未作类型转换
/usr/local/php/include/php/Zend/zend_list.h:59: 附注：需要类型‘struct zend_resource *’，但实参的类型为‘int’
/root/scws-1.2.1/phpext/php_scws.c: 在函数‘zif_scws_set_charset’中:
/root/scws-1.2.1/phpext/php_scws.c:313: 警告：传递‘zend_hash_find’的第 2 个参数时在不兼容的指针类型间转换
/usr/local/php/include/php/Zend/zend_hash.h:168: 附注：需要类型‘struct zend_string *’，但实参的类型为‘char *’
/root/scws-1.2.1/phpext/php_scws.c:313: 错误：提供给函数‘zend_hash_find’的实参太多
/root/scws-1.2.1/phpext/php_scws.c:313: 警告：比较指针和整数
/root/scws-1.2.1/phpext/php_scws.c:325: 错误：expected expression before ‘struct’
/root/scws-1.2.1/phpext/php_scws.c: 在函数‘zif_scws_add_dict’中:
/root/scws-1.2.1/phpext/php_scws.c:345: 警告：传递‘zend_hash_find’的第 2 个参数时在不兼容的指针类型间转换
/usr/local/php/include/php/Zend/zend_hash.h:168: 附注：需要类型‘struct zend_string *’，但实参的类型为‘char *’
/root/scws-1.2.1/phpext/php_scws.c:345: 错误：提供给函数‘zend_hash_find’的实参太多
/root/scws-1.2.1/phpext/php_scws.c:345: 警告：比较指针和整数
/root/scws-1.2.1/phpext/php_scws.c:357: 错误：expected expression before ‘struct’
/root/scws-1.2.1/phpext/php_scws.c: 在函数‘zif_scws_set_dict’中:
/root/scws-1.2.1/phpext/php_scws.c:396: 警告：传递‘zend_hash_find’的第 2 个参数时在不兼容的指针类型间转换
/usr/local/php/include/php/Zend/zend_hash.h:168: 附注：需要类型‘struct zend_string *’，但实参的类型为‘char *’
/root/scws-1.2.1/phpext/php_scws.c:396: 错误：提供给函数‘zend_hash_find’的实参太多
/root/scws-1.2.1/phpext/php_scws.c:396: 警告：比较指针和整数
/root/scws-1.2.1/phpext/php_scws.c:408: 错误：expected expression before ‘struct’
/root/scws-1.2.1/phpext/php_scws.c: 在函数‘zif_scws_set_rule’中:
/root/scws-1.2.1/phpext/php_scws.c:446: 警告：传递‘zend_hash_find’的第 2 个参数时在不兼容的指针类型间转换
/usr/local/php/include/php/Zend/zend_hash.h:168: 附注：需要类型‘struct zend_string *’，但实参的类型为‘char *’
/root/scws-1.2.1/phpext/php_scws.c:446: 错误：提供给函数‘zend_hash_find’的实参太多
/root/scws-1.2.1/phpext/php_scws.c:446: 警告：比较指针和整数
/root/scws-1.2.1/phpext/php_scws.c:458: 错误：expected expression before ‘struct’
/root/scws-1.2.1/phpext/php_scws.c: 在函数‘zif_scws_set_ignore’中:
/root/scws-1.2.1/phpext/php_scws.c:495: 警告：传递‘zend_hash_find’的第 2 个参数时在不兼容的指针类型间转换
/usr/local/php/include/php/Zend/zend_hash.h:168: 附注：需要类型‘struct zend_string *’，但实参的类型为‘char *’
/root/scws-1.2.1/phpext/php_scws.c:495: 错误：提供给函数‘zend_hash_find’的实参太多
/root/scws-1.2.1/phpext/php_scws.c:495: 警告：比较指针和整数
/root/scws-1.2.1/phpext/php_scws.c:507: 错误：expected expression before ‘struct’
/root/scws-1.2.1/phpext/php_scws.c: 在函数‘zif_scws_set_multi’中:
/root/scws-1.2.1/phpext/php_scws.c:522: 警告：传递‘zend_hash_find’的第 2 个参数时在不兼容的指针类型间转换
/usr/local/php/include/php/Zend/zend_hash.h:168: 附注：需要类型‘struct zend_string *’，但实参的类型为‘char *’
/root/scws-1.2.1/phpext/php_scws.c:522: 错误：提供给函数‘zend_hash_find’的实参太多
/root/scws-1.2.1/phpext/php_scws.c:522: 警告：比较指针和整数
/root/scws-1.2.1/phpext/php_scws.c:534: 错误：expected expression before ‘struct’
/root/scws-1.2.1/phpext/php_scws.c: 在函数‘zif_scws_set_duality’中:
/root/scws-1.2.1/phpext/php_scws.c:552: 警告：传递‘zend_hash_find’的第 2 个参数时在不兼容的指针类型间转换
/usr/local/php/include/php/Zend/zend_hash.h:168: 附注：需要类型‘struct zend_string *’，但实参的类型为‘char *’
/root/scws-1.2.1/phpext/php_scws.c:552: 错误：提供给函数‘zend_hash_find’的实参太多
/root/scws-1.2.1/phpext/php_scws.c:552: 警告：比较指针和整数
/root/scws-1.2.1/phpext/php_scws.c:564: 错误：expected expression before ‘struct’
/root/scws-1.2.1/phpext/php_scws.c: 在函数‘zif_scws_send_text’中:
/root/scws-1.2.1/phpext/php_scws.c:579: 警告：传递‘zend_hash_find’的第 2 个参数时在不兼容的指针类型间转换
/usr/local/php/include/php/Zend/zend_hash.h:168: 附注：需要类型‘struct zend_string *’，但实参的类型为‘char *’
/root/scws-1.2.1/phpext/php_scws.c:579: 错误：提供给函数‘zend_hash_find’的实参太多
/root/scws-1.2.1/phpext/php_scws.c:579: 警告：比较指针和整数
/root/scws-1.2.1/phpext/php_scws.c:591: 错误：expected expression before ‘struct’
/root/scws-1.2.1/phpext/php_scws.c:593: 警告：传递‘zval_get_type’的第 1 个参数时在不兼容的指针类型间转换
/usr/local/php/include/php/Zend/zend_types.h:389: 附注：需要类型‘const struct zval *’，但实参的类型为‘struct zval **’
/root/scws-1.2.1/phpext/php_scws.c:593: 警告：传递‘zval_get_type’的第 1 个参数时在不兼容的指针类型间转换
/usr/local/php/include/php/Zend/zend_types.h:389: 附注：需要类型‘const struct zval *’，但实参的类型为‘struct zval **’
/root/scws-1.2.1/phpext/php_scws.c:593: 警告：传递‘_convert_to_string’的第 1 个参数时在不兼容的指针类型间转换
/usr/local/php/include/php/Zend/zend_operators.h:250: 附注：需要类型‘struct zval *’，但实参的类型为‘struct zval **’
/root/scws-1.2.1/phpext/php_scws.c: 在函数‘zif_scws_get_result’中:
/root/scws-1.2.1/phpext/php_scws.c:615: 警告：传递‘zend_hash_find’的第 2 个参数时在不兼容的指针类型间转换
/usr/local/php/include/php/Zend/zend_hash.h:168: 附注：需要类型‘struct zend_string *’，但实参的类型为‘char *’
/root/scws-1.2.1/phpext/php_scws.c:615: 错误：提供给函数‘zend_hash_find’的实参太多
/root/scws-1.2.1/phpext/php_scws.c:615: 警告：比较指针和整数
/root/scws-1.2.1/phpext/php_scws.c:625: 错误：expected expression before ‘struct’
/root/scws-1.2.1/phpext/php_scws.c:635:68: 错误：宏“add_assoc_stringl”传递了 5 个参数，但只需要 4 个
/root/scws-1.2.1/phpext/php_scws.c:635: 错误：‘add_assoc_stringl’未声明(在此函数内第一次使用)
/root/scws-1.2.1/phpext/php_scws.c:639:78: 错误：宏“add_assoc_stringl”传递了 5 个参数，但只需要 4 个
/root/scws-1.2.1/phpext/php_scws.c: 在函数‘zif_scws_get_tops’中:
/root/scws-1.2.1/phpext/php_scws.c:661: 警告：传递‘zend_hash_find’的第 2 个参数时在不兼容的指针类型间转换
/usr/local/php/include/php/Zend/zend_hash.h:168: 附注：需要类型‘struct zend_string *’，但实参的类型为‘char *’
/root/scws-1.2.1/phpext/php_scws.c:661: 错误：提供给函数‘zend_hash_find’的实参太多
/root/scws-1.2.1/phpext/php_scws.c:661: 警告：比较指针和整数
/root/scws-1.2.1/phpext/php_scws.c:673: 错误：expected expression before ‘struct’
/root/scws-1.2.1/phpext/php_scws.c:684:45: 错误：宏“add_assoc_string”传递了 4 个参数，但只需要 3 个
/root/scws-1.2.1/phpext/php_scws.c:684: 错误：‘add_assoc_string’未声明(在此函数内第一次使用)
/root/scws-1.2.1/phpext/php_scws.c:687:78: 错误：宏“add_assoc_stringl”传递了 5 个参数，但只需要 4 个
/root/scws-1.2.1/phpext/php_scws.c:687: 错误：‘add_assoc_stringl’未声明(在此函数内第一次使用)
/root/scws-1.2.1/phpext/php_scws.c: 在函数‘zif_scws_has_word’中:
/root/scws-1.2.1/phpext/php_scws.c:706: 警告：传递‘zend_hash_find’的第 2 个参数时在不兼容的指针类型间转换
/usr/local/php/include/php/Zend/zend_hash.h:168: 附注：需要类型‘struct zend_string *’，但实参的类型为‘char *’
/root/scws-1.2.1/phpext/php_scws.c:706: 错误：提供给函数‘zend_hash_find’的实参太多
/root/scws-1.2.1/phpext/php_scws.c:706: 警告：比较指针和整数
/root/scws-1.2.1/phpext/php_scws.c:718: 错误：expected expression before ‘struct’
/root/scws-1.2.1/phpext/php_scws.c: 在函数‘zif_scws_get_words’中:
/root/scws-1.2.1/phpext/php_scws.c:739: 警告：传递‘zend_hash_find’的第 2 个参数时在不兼容的指针类型间转换
/usr/local/php/include/php/Zend/zend_hash.h:168: 附注：需要类型‘struct zend_string *’，但实参的类型为‘char *’
/root/scws-1.2.1/phpext/php_scws.c:739: 错误：提供给函数‘zend_hash_find’的实参太多
/root/scws-1.2.1/phpext/php_scws.c:739: 警告：比较指针和整数
/root/scws-1.2.1/phpext/php_scws.c:751: 错误：expected expression before ‘struct’
/root/scws-1.2.1/phpext/php_scws.c:759:45: 错误：宏“add_assoc_string”传递了 4 个参数，但只需要 3 个
/root/scws-1.2.1/phpext/php_scws.c:759: 错误：‘add_assoc_string’未声明(在此函数内第一次使用)
/root/scws-1.2.1/phpext/php_scws.c:762:78: 错误：宏“add_assoc_stringl”传递了 5 个参数，但只需要 4 个
/root/scws-1.2.1/phpext/php_scws.c:762: 错误：‘add_assoc_stringl’未声明(在此函数内第一次使用)
/root/scws-1.2.1/phpext/php_scws.c:776:22: 错误：宏“RETURN_STRING”传递了 2 个参数，但只需要 1 个
/root/scws-1.2.1/phpext/php_scws.c: 在函数‘zif_scws_version’中:
/root/scws-1.2.1/phpext/php_scws.c:776: 错误：‘RETURN_STRING’未声明(在此函数内第一次使用)
make: *** [php_scws.lo] 错误 1

**Comment by hightman** [comment]
1.最新版本 1.2.3
2.需要用PHP自带的 phpize 初始化，并且编译是用 --with-php-config 指定到对应的 php-config
