### ISSUE TITLE
ubuntu18安装后执行命令报错

### ISSUE THREAD

**Issue by YeDongaidiiqu** [hightman/scws#64]
安装完成后执行命令报如下错误
scws: error while loading shared libraries: libscws.so.1: cannot open shared object file: No such file or directory

**Comment by waitingsong** [comment]
安装有问题吧， 动态库文件不存在。

**Comment by YeDongaidiiqu** [comment]
> 安装有问题吧， 动态库文件不存在。

不是，没有指定绝对路径

**Comment by waitingsong** [comment]
那也许这个文件的安装路径不是系统默认的搜索路径。

**Comment by xiaohui-zhangxh** [comment]
安装之后，执行一次 `sudo ldconfig`

**Comment by mitoop** [comment]
@xiaohui-zhangxh 老哥这个有效
