### ISSUE TITLE
如何自定义rules.ini

### ISSUE THREAD

**Issue by liangkdm** [hightman/scws#71]
你好，请问一下如何自定义rules.ini 文件。主要是
;
; 词性语法规则表
;
[attrs]
; c 是连词
n + f(1) = 300
n + m(1) = 500
n(1) + v = 100
n + v(1) = 10
r + n(1) = 1000
r(1) + n = 100
d(1) + r = 100
d(1) + v = 100
v(1) + r = 100
n + m(1) = 500
v + f(1) = 30
v(1) + m = 100
v(1) + n = 3
a + u(1) = 5
v + n(1) = 5
u(1) + a = 2
c(1) + * = 50
* + c(1) = 50
这个规则没有看明白什么意思。

**Comment by hightman** [comment]
括号内是字数，c(1)表示一个字的连词

发自我的 iPhone6艹

**Comment by liangkdm** [comment]
thanks @
