### ISSUE TITLE
大佬，php8+的编译能不能适配一下~~~

### ISSUE THREAD

**Issue by xiaqii** [hightman/scws#72]
大佬，php8+的编译能不能适配一下~~~
或者可以做成一个简单的单机服务监听端口，
提交内容得到分词结果，
这样以后也不用作为php扩展了

**Comment by hightman** [comment]
好的，我找时间尝试一下

**Comment by hightman** [comment]
已经修复，参见 781f695a08e951d587374b69965f3992b62c956c 请下载 github 代码重新编译即可。
