### ISSUE TITLE
解压XDB之后权限问题导致分词错误

### ISSUE THREAD

**Issue by fifsky** [hightman/scws#9]
我是centos6.4的系统，使用root权限下载utf8 gbk两个xdb文件之后，将官方的demo拷贝回来测试发现分词和官方不一致
“我是一个中国人,我会C++语言,我也有很多T恤衣”
除了“一个”被分词了，其他全部是单字，后来发现XDB的权限很奇怪
-rw-------  1    501 games  13245765 1月   8 2013 dict.xdb
chown root:root dict.xdb
chmod 644 dict.xdb

UTF同上
修改之后测试就和官方一致了
记录在这里，希望能帮助到其他人^_^

**Comment by hightman** [comment]
线上的包改过了。
